more debug output

diff --git a/utils/pakistan-censorship-testing/files/usr/bin/pakistan-censorship-testing b/utils/pakistan-censorship-testing/files/usr/bin/pakistan-censorship-testing
--- a/utils/pakistan-censorship-testing/files/usr/bin/pakistan-censorship-testing
+++ b/utils/pakistan-censorship-testing/files/usr/bin/pakistan-censorship-testing
@@ -3,7 +3,7 @@
 ### giuseppe.aceto@unina.it
 
 client=booid ; # Ash-based BISmark script
-clientver=12 ; # based on ashooni ver 12
+clientver=13 ; # now with more debugging info!
 clientnotes="pktest-bismark" ; # WARN: underscore forbidden XXX
 testname=webcontent
 testver=1.15 ; # fixed nslookup parsing
@@ -189,7 +189,7 @@ fi
 	inputfile="${inputcc}_${inputcounter}_inputfile.gz"
 	inputurl="$remote_inputfile_path/$inputfile"
 	rm dwnlresult.header > /dev/null 2>&1
-	$CURL --max-time 20 -o "$inputfile" -D dwnlresult.header --url "$inputurl" ; dwlresult=$?
+	$CURL --max-time 20 -o "$inputfile" -D dwnlresult.header --url "$inputurl" >&2 ; dwlresult=$?
 	httpcode=`awk 'FNR == 1 {print $2}' dwnlresult.header`
 	rm dwnlresult.header > /dev/null 2>&1
 	if [ ! $dwlresult -eq 0 ] || [ ! $httpcode -eq 200 ]; then
@@ -231,7 +231,9 @@ Mozilla/5.0 (Windows; U; Windows NT 5.1; de; rv:1.9.1.7) Gecko/20091221 Firefox/
 
 ## bismark functions:
 if [ -e /usr/lib/bismark/functions.inc.sh ]; then
+	echo "loading BISmark functions" >&2
 	. /usr/lib/bismark/functions.inc.sh
+	echo "BISmark functions loaded" >&2
 else
 	echo "mutual exclusion lock functions are missing!" >&2
 	exit 42 ; # -------------------------------------------------------------->>
@@ -488,10 +490,13 @@ webcontent(){
 
 #START SCRIPT
 
+echo "expiring previous active locks ..." >&2
 expire_active_measurements_lock ; # just in case
+echo "try to acquire active locks ..." >&2
 if ! acquire_active_measurements_lock $active_measurement_utils_list ; then
 	exit 42 ; # ---------------------------------------------------------->>
 fi
+echo "active lock acquired ..." >&2
 
 if ! [ "$inputfile" = "" ]; then
 	test_start_ts=`date +%s`; export test_start_ts
@@ -573,7 +578,9 @@ else
 fi
 
 # end of critical section. after this just an ftp upload is performed.
+echo "releasing active lock ..." >&2
 release_active_measurements_lock
+echo "lock released." >&2
 
 if [ $archive_stdout_stderr -eq 1 ]; then
 	# close report files and restore redirected descriptors:
@@ -601,23 +608,30 @@ rm $inputfile
 
 # archive results and WARN about where they are.
 cd $persistentdir
-echo "compressing results in `pwd` ..."
+echo "compressing results in `pwd` ..." >&2
 
 if tar -czf $result_test_arch tempdir_${ts} ; then
-	echo "Removing all temporary files and results in $cleanthisdir ..."
-	rm -fr "$cleanthisdir" && echo "... done." || echo "ERROR $? removing temp files in $cleanthisdir";
+	echo "Removing all temporary files and results in $cleanthisdir ..." >&2
+	rm -fr "$cleanthisdir" && echo "... done." >&2 || echo "ERROR $? removing temp files in $cleanthisdir" >&2
 else
-	echo "ERROR $? in creating the archive of results in $cleanthisdir";
+	echo "ERROR $? in creating the archive of results in $cleanthisdir" >&2 ;
 	# TODO optionally remove everything to avoid piling-up garbage
-	echo "WARNING temporary files and results are still in $cleanthisdir";
-	echo "ABORT."; exit 111;
+	echo "WARNING temporary files and results are still in $cleanthisdir" >&2 ;
+	echo "ABORT." >&2 ; exit 111;
 fi
-echo ; echo "results in $result_test_arch"
+{ echo ; echo "results in $result_test_arch"; } >&2
 
 	#send results to server
-	echo; echo "Uploading of results to the server..." >&2
-	$CURL --user ftpuser:hobbitftp1 \
+	{ echo; echo "Uploading of results to the server..." ; } >&2
+if $CURL --user ftpuser:hobbitftp1 \
 		--max-time $maximum_service_connections_time \
-		-T $result_test_arch $ftp ;
+		-T $result_test_arch $ftp >&2 ;
+	then echo "Results SUCCESSFULLY uploaded to the server."  >&2
+	else echo "Upload of results FAILED. "  >&2
+fi
 
-		rm -fr "$result_test_arch"
+echo "Removing result file $result_test_arch ..." >&2
+if rm -fr "$result_test_arch" >&2
+	then echo "removed." >&2
+	else echo "Error $? removing result file. This may be BAD." >&2
+fi
